- application/common/models/Method.php
- application/common/models/User.php
- application/frontend/config/main.php
- application/frontend/controllers/SiteController.php
@fillup requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/silinternational/idp-pw-api/
> Scrutinizer Auto-Fixes

- Dockerfile
- Makefile
- application/common/config/main.php
- application/common/helpers/Utils.php
- application/common/models/Reset.php
- application/console/controllers/CronController.php
- application/run-cron.sh
- application/run.sh
- application/tests/unit/common/models/ResetTest.php
- docker-compose.yml
- dockerbuild/idp-cron
Currently adding a cron job to retry emails that get queued up. It will attempt to retry the oldest five emails every minute. Emails are only queued if initial attempt to send fails, so far in testing we have not seen one fail so this is a backup process just in case.
> Adding cron support

- application/common/helpers/Utils.php
- application/composer.lock
Also adding user agent to log when missing clientId exception occurs
> updated saml auth missing attribute exception

- application/composer.lock
This is to improve the logging when Nexmo returns an error code indicating that we sent them an invalid phone number.
> Pull in updated Nexmo phone verification code.

- Makefile
- application/composer.json
- application/composer.lock
- application/run-tests.sh
- application/tests/features/Context/MultipleContext.php
- application/tests/features/DummyPasswordStore.php
- application/tests/features/behat.yml
- application/tests/features/multiple.feature
- application/tests/unit/common/components/FakeIdBrokerClient.php
- application/tests/unit/common/components/IdBrokerPwTest.php
- application/tests/unit/common/components/LdapTest.php
Brought in PHPUnit tests from:
- idp-pw-api-passwordstore-id-broker
- idp-pw-api-passwordstore-ldap
and Behat tests from:
- idp-pw-api-passwordstore-multiple
> Integrate Password Store tests

- api.raml
- application/common/models/Method.php
- application/common/models/User.php
- application/frontend/controllers/MethodController.php
- application/frontend/messages/fr/app.php
- Add exception handling for all known 400-level status codes on `method` endpoints.
- Fill in all known responses in RAML file
- Clean up 'verified' references `getMethodsAndPersonnelEmails()`
> Improve exception handling

- application/common/components/personnel/IdBroker.php
- application/common/components/personnel/PersonnelInterface.php
- application/common/components/personnel/PersonnelUser.php
- application/common/models/User.php
- application/composer.lock
- application/run-tests-api.sh
- application/tests/features/behat.yml
- application/tests/helpers/BrokerFakeData.php
- application/tests/mock/personnel/Component.php
- application/tests/unit/common/components/IdBrokerTest.php
- application/tests/unit/common/models/UserTest.php
- codeship-services.yml
- docker-compose.yml
- Send `PUT /user` to broker when the `do_not_disclose` flag changes.
- Save `do_not_disclose` flag locally when reading from broker.
- minor test improvements
> Synchronize do_not_disclose flag with broker

- api.raml
- application/composer.lock
- application/frontend/config/main.php
- application/frontend/controllers/MfaController.php
- application/frontend/messages/fr/app.php
- codeship-services.yml
- docker-compose.yml
Created a new PUT /mfa/{mfaId} endpoint to change the label of existing MFA options.
> Add MFA label update

- application/common/components/personnel/IdBroker.php
- application/common/config/main.php
- application/run-tests.sh
- application/tests/helpers/BrokerUtils.php
- application/tests/unit/common/components/IdBrokerTest.php
Refactored ID Broker configuration
- consolidated configuration into a common entry in `$app->params`
- moved creation of personnel ID Broker client into `init()`
> ID Broker refactoring

- application/common/mail/reset/on-behalf.php
- application/common/models/Password.php
- application/composer.json
* Check submitted password against those given as examples in a video about secure passwords.
> add password checks

- application/common/models/Password.php
- application/composer.json
- application/composer.lock
- application/frontend/messages/fr/app.php
Found a HIBP PHP library that is a better fit. Uses Guzzle and implements the API more fully. Doesn't lock to a specific API version, though.
> use the haveibeenpwned.com API to test new passwords

- CHANGELOG.md
- Dockerfile
- application/common/helpers/Utils.php
- application/composer.json
- application/composer.lock
- application/frontend/config/main.php
- codeship-services.yml
- docker-compose.yml
- local.env.dist
- test.env
Updated verison of PR #69. Merged feature/memcache with current develop branch, tested with [idp-profile-ui](https://github.com/silinternational/idp-profile-ui), and added `ext-memcache` to `composer.json`.
> use memcache for session storage

- CHANGELOG.md
- README.md
- application/.gitignore
- application/common/components/passwordStore/Google.php
- application/common/components/passwordStore/IdBroker.php
- application/common/components/passwordStore/Ldap.php
- application/common/components/passwordStore/Multiple.php
- application/common/components/passwordStore/PasswordStoreException.php
- application/common/components/passwordStore/PasswordStoreInterface.php
- application/common/models/Password.php
- application/frontend/messages/en/app.php
- application/tests/features/Context/MultipleContext.php
- application/tests/features/DummyPasswordStore.php
- application/tests/features/multiple.feature
- application/tests/mock/passwordstore/Component.php
Attempt to set password in every passwordStore component even if one fails. Provide messaging to indicate which failed and which succeeded.
> Allow partial success in Multiple component

- application/common/config/main.php
- application/composer.lock
- application/frontend/config/main.php
Configure Yii logging to immediately output log messages, rather than cache them up. Prevents messages from being lost if the container crashes (e.g. out of memory).
> no log delay

- application/common/components/passwordStore/Google.php
- application/common/config/local.php.dist
- application/tests/features/Context/GoogleContext.php
- application/tests/features/google.feature
searching only by externalId has been found to be unreliable
> use both externalId and email to find Google users

- CHANGELOG.md
- application/frontend/controllers/SiteController.php
- Removed redundant error log entry in /site/system-status
> Release 6.0.2 - remove redundant error log entry

- application/common/config/main.php
- application/frontend/controllers/AuthController.php
- Don't send email alert for 403 errors.
- Don't send email alert for invite code expired error.
> fewer alerts

- application/tests/mock/personnel/Component.php
> Fix the mock test personnel component so that the tests pass again.

- Dockerfile
- README.md
- application/run.sh
- local.env.dist
- Read environment variables from AppConfig if `APP_ID` is set
---
> add AppConfig

- application/tests/api/ResetCest.php
- used for loop to clean up test
---
> use for loop in test9

- application/common/models/User.php
- application/composer.lock
- application/dependencies.json
- Dependency updates, including yii2 update for CVE-2024-4990 ([IDP-1137](https://itse.youtrack.cloud/issue/IDP-1137))
- Refactor one unit test
> Release 7.0.1 -- dependency updates

- application/common/config/main.php
- Add 401, 403, and 409 to Sentry logger exception list
> Release 7.0.2 -- don't send user errors to Sentry

- .github/workflows/test-and-publish.yml
- application/frontend/controllers/MethodController.php
- application/frontend/controllers/MfaController.php
- application/frontend/controllers/PasswordController.php
- application/frontend/controllers/ResetController.php
[IDP-1223](https://itse.youtrack.cloud/issue/IDP-1223) trim whitespace from idp-pw-api user input
---
- Added GitHub Actions timeout.
- Added semantic version tags to Docker image (e.g. 1.2 for tag 1.2.3).
- Trim whitespace from user-submitted strings. 
- Code whitspace inconsistencies fixed by phpStorm.
---
> Release 7.0.3 -- trim whitespace

- .github/workflows/test-and-publish.yml
Added
Added a step to push the Docker image to GitHub Container Registry
-
-
-
- 
-
---
> Release 7.0.4 -- Push image to GHCR.io 

- actions-services.yml
- docker-compose.yml
- change develop tags to major version for dev and test containers
---
> Release 7.0.6 - fix build and test

- actions-services.yml
- docker-compose.yml
[ITSE-866](https://itse.youtrack.cloud/issue/ITSE-866) Stop using our "data" volume docker image
---
- Specify MariaDB version 10 for development and test
- Removed the data container from the Docker Compose environment
> remove the data container from Docker Compose environment

- docker-compose.yml
Incremental progress towards addressing
---
- Use the standard, cross-platform phpMyAdmin Docker image
- For Docker images that only have a linux/amd64 version, use that
---
> Release 7.0.9 - Fix local development for Mac chips

- application/common/components/auth/Saml.php
- application/composer.json
- application/composer.lock
- application/dependencies.json
---
- Update SAML2 library from v3 to v4
---
> Release 7.0.11-pre - Upgrade SAML2 library (PRE-RELEASE)

- application/common/components/auth/Saml.php
---
- Do not change signature of interface methods we implement
- Add missing use import for a SAML2 class
---
> Release 7.0.11-pre.1 - Fix SAML2 v4 upgrade

- application/common/components/auth/SamlContainer.php
---
- Also update SamlContainer class based on newer version in Mail Admin
---
> Release 7.0.11-pre.2 - Fix SamlContainer class for SAML2 v4 upgrade

- README.md
- application/common/components/passwordStore/Ldap.php
> Release 7.2.0 - Deprecate LDAP

- application/common/config/main.php
- application/run.sh
- Include app version in log messages
---
> Release 7.2.2 -- include app version in log messages

- application/common/components/passwordStore/Ldap.php
https://itse.youtrack.cloud/issue/IDP-1473
---
- LDAP client is now nullable and initialized to null
---
> Release 7.3.3 - Fix LDAP client not being initialized

- application/common/components/passwordStore/Ldap.php
https://support.gtis.sil.org/issue/IDP-1540
---
- Attempt to fix LDAP again by using LDAP_Entry model to generate query
---
> Release 7.3.5 - use LDAP_Entry model to generate query

- application/common/components/passwordStore/Google.php
- application/composer.json
- application/composer.lock
- application/dependencies.json
- application/frontend/messages/en/app.php
- application/frontend/messages/en/model.php
- application/frontend/messages/en/yii.php
- application/frontend/messages/es/app.php
- application/frontend/messages/es/model.php
- application/frontend/messages/es/yii.php
- application/frontend/messages/fr/app.php
- application/frontend/messages/fr/model.php
- application/frontend/messages/fr/yii.php
- application/frontend/messages/ko/app.php
- application/frontend/messages/ko/model.php
- application/frontend/messages/ko/yii.php
- application/requirements.php
- application/tests/codeception/bin/_bootstrap.php
- application/tests/codeception/common/templates/fixtures/user.php
- application/tests/codeception/config/acceptance.php
- application/tests/codeception/config/common/unit.php
- application/tests/codeception/config/config.php
- application/tests/codeception/config/console/unit.php
- application/tests/codeception/config/functional.php
- application/tests/codeception/config/unit.php
(Maintaining 7.2.x branch a little longer, to address some LDAP connection issues, re: [IDP-1540](https://support.gtis.sil.org/issue/IDP-1540))
---
- Update dependencies of 7.2.x branch of idp-pw-api
- Remove old (unneeded) `fillup/fake-bower-assets` dependency
---
> Release 7.2.3 - Update dependencies of 7.2.x branch
