application/common/models/Password.php

The PasswordReuseException is either not getting thrown properly or is not getting caught, so updating the default error when setting password fails on server to tell user not to try different password if current has been used.

Updating password server error message for reuse issue

---

application/common/config/main.php
application/frontend/controllers/ResetController.php
local.env.dist

When running locally for dev without a UI its a pain to deal with recaptcha, this will allow disabling the requirement for it. I added it as a separate var rather than conditionally based on the recaptcha key and secret being present to ensure it is only disabled intentionally, not due to forgetting one of the other vars.

added env var to enable/disable requiring recaptcha, default is required

---

application/composer.lock

This is to update the simplesamlphp/saml2 library in our legacy version of idp-pw-api.

Update SAML2 dependency

---

Vagrantfile
application/composer.json
application/composer.lock
application/frontend/config/main.php
application/tests/api/FixtureHelper.php
local.env.dist

**Summary:**
* Update Yii2 to a non-vulnerable version
* Add optional `COOKIE_VALIDATION_KEY` env. var
* Fix tests (by unloading fixtures before reloading them)
These are all changes that we have already done on our current (aka. non-legacy) branch of this code.
Since this does add a new feature (cookie validation), I'm bumping the middle "number" of the version (`legacy.1.1` to `legacy.2.0`).

Release `legacy.2.0`

---

application/run.sh
local.env.dist

Added configuration for "remote" debugging while running in a Docker container. 
To set up debugging, do the following:
1. Add physical machine's IP address (or VM if running on macOS or Windows) into `REMOTE_DEBUG_IP` in `local.env` and set `APP_ENV` to `dev`.
2. In PHPStorm go to: Preferences > Languages & Frameworks > PHP > Debug > DBGp Proxy and set Host to the same IP address, and port to 9000.
3. Start PHPStorm listening by clicking the "listen" button on the toolbar.

Add configuration for debugging

---

application/common/config/test.php
application/tests/api/PasswordCest.php
codeship-services.yml
docker-compose.yml

Change `passwordStore` component from a test double to the real ID Broker `passwordStore` component, and point it at the broker test container, as previously defined in `common/config/main.php`
Also changed the test passwords to random strings so that retesting with residual data in the database doesn't cause a password reuse exception.

Use broker container for passwordStore tests

---

application/frontend/components/BaseRestController.php
application/frontend/config/main.php

The Yii CORS filter didn't work on error responses. This PR replaces the CORS filter with unconditionally adding the CORS headers to all responses.

Send CORS headers on all responses

---

application/common/components/passwordStore/IdBroker.php
application/common/models/Password.php

In order to present the user with an opportunity to enter a new password, the HTTP status code for password reuse should be 409 instead of 400.

Change password reuse error

---

application/common/models/User.php
application/frontend/controllers/AuthController.php

If the `auth_type` is `LOGIN` (password), and the user sets a new password, destroy the `access_token` to force a new login.

destroy auth token on password change

---

application/common/config/main.php
application/common/models/Reset.php
application/console/controllers/CronController.php
application/frontend/controllers/ResetController.php
dockerbuild/idp-cron

Rather than a "lazy delete" of old records, we now use cron to purge old records. Also, there is now a concept of a "grace period". After a reset has expired, we'll keep it for a little while in case the user clicks on an old link. (See PR #141)

purge old, expired resets by cron job

---

application/common/components/passwordStore/Google.php
application/common/components/passwordStore/IdBroker.php
application/common/components/passwordStore/Ldap.php
application/common/components/passwordStore/Multiple.php
application/common/components/passwordStore/PasswordStoreInterface.php
application/common/config/main.php
application/common/models/Method.php
application/common/models/Password.php
application/common/models/User.php
application/console/controllers/CronController.php
application/frontend/controllers/MethodController.php
application/frontend/controllers/MfaController.php
application/frontend/controllers/ResetController.php
application/tests/features/DummyPasswordStore.php
application/tests/mock/passwordstore/Component.php

In order to block a password reset for locked accounts, we need to have a method on `passwordStore` get the lock status. Previously, `getMeta()` was used for this, but a dedicated getter method is cleaner.

Create isLocked method on passwordStore interface

---

application/common/config/local.php.dist
application/common/config/main.php
application/common/helpers/Utils.php
application/common/models/Password.php
application/frontend/messages/fr/app.php
application/tests/api/PasswordCest.php
application/tests/unit/common/helpers/UtilsTest.php
application/tests/unit/common/models/PasswordTest.php
codeship-services.yml
local.env.dist
test.env

Remove `minNum`, `minUpper`, and `minSpecial` password rules. `minLength`, `maxLength`, and `minScore` are the remaining rules.

remove unnecessary password rules

---

application/common/components/personnel/IdBroker.php
application/composer.json
application/composer.lock
application/tests/unit/common/components/IdBrokerPwTest.php
application/tests/unit/common/components/IdBrokerTest.php

Use mocked class instead of an actual `idp-id-broker` Docker container. The model unit tests and the `api` Codeception suite still exercise the broker API interface.

Redesign ID Broker personnelStore and passwordStore component tests

---

application/common/components/passwordStore/Ldap.php
application/composer.json

**Added:**
- Will properly encode passwords for storing in the `unicodePwd` field when applicable.

Support `unicodePwd` field in idp-pw-api Ldap password store

---

application/frontend/controllers/AuthController.php
application/tests/api/AuthCest.php

A user will see an error page from the API if they sit on the IDP login prompt long enough for the session to expire, and then proceed with the login attempt. This patch does a redirect back to a profile UI page, which should restart the login process.

patch to help recover from an expired login session

---

.gitignore
application/common/components/passwordStore/Ldap.php

Iterate through the list of hosts and hold on to the first one that works so it doesn't have to do that each time `connect` is called, which can be several times in one request.

allow a list of hosts in ldap config

---

CHANGELOG.md
LICENSE.txt

- Allow LDAP host name to be a list of hostname strings as well as a single string for backward compatibility

Release 5.4.0

---

CHANGELOG.md
application/common/config/main.php
application/frontend/controllers/SiteController.php

Use http 502 (bad gateway) for email-service status check and database status check, and exclude it from the email alert. Since this is triggered either by NodePing or by AWS ECS, a true outage will be reported or addressed by those services.

Don't send email alert for bad email-service check

---

application/common/models/Password.php
application/tests/api/PasswordCest.php
application/tests/api/fixtures/data/User.php

This is a fix for https://trello.com/c/V1tb0LAo/556-dont-prevent-password-from-including-first-last-name-if-that-name-is-less-than-3-characters-long

allow a short name to be contained in a password

---

application/common/config/main.php

- Simplification: use YII_ENV in main.php
---

use YII_ENV instead of APP_ENV

---

application/common/config/main.php

- Do net send HTTP request body in log data sent to Sentry
[IDP-862](https://itse.youtrack.cloud/issue/IDP-862)

IDP-862 -- configure Sentry to not send request bodies in log data

---

application/common/config/main.php

- Configure Sentry to not send request body data to Sentry logging servers.
---

Release 6.6.3 -- don't log request data

---

README.md
application/common/models/Password.php
application/frontend/messages/en/app.php
application/frontend/messages/es/app.php
application/frontend/messages/fr/app.php
application/frontend/messages/ko/app.php
application/tests/unit/common/models/PasswordTest.php

- Added password validation to reject a password containing a null byte.
[IDP-125](https://itse.youtrack.cloud/issue/IDP-125)
---

validate password does not contain null byte

---

application/common/config/main.php
application/common/models/Password.php
application/frontend/messages/en/app.php
application/frontend/messages/es/app.php
application/frontend/messages/fr/app.php
application/frontend/messages/ko/app.php
application/tests/unit/common/models/PasswordTest.php
local.env.dist

- Add validation option to require alpha and numeric chars
Note: Reference for regex is [here](https://www.php.net/manual/en/regexp.reference.unicode.php).
---

IDP-1076: Add option to require alpha and numeric chars for PCI 4.0 compliance

---

.github/CODEOWNERS
.github/pull_request_template.md
.github/workflows/test-and-publish.yml

- Also push a major-version tag 
- Run CI tests on all branches

Release 7.0.5 -- test on all branches, but only push image for tags

---

Makefile
README.md
application/common/components/passwordStore/Google.php
application/common/config/local.php.dist
application/common/config/main.php
application/common/models/User.php
application/composer.json
application/composer.lock
application/dependencies.json
application/frontend/messages/en/app.php
application/frontend/messages/es/app.php
application/frontend/messages/fr/app.php
application/frontend/messages/ko/app.php

[IDP-779](https://itse.youtrack.cloud/issue/IDP-779) Sentry log events are sometimes "unlabeled"
---
- Added the idp name to Sentry issues as a tag. This is searchable, sortable, and more visible than a context entry.
- Log a useful message to Sentry in cases where no explicit "message" key is included
- Fixed error instances that had neither "message" nor "error"
- Fixed "composershow" make target to generate valid json
- Replace "G Suite" with "Google Workspace"
- Don't report status 400 errors
---

Fix Sentry logging details

---

application/common/models/User.php

[Sentry Issue](https://itse.sentry.io/issues/6130254845/?project=4506061422264322&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=1)
---
- Fixed array passed as error message

encode the array before assigning it to 'error'

---

docker-compose.yml

- #302 
---
Incremental progress towards addressing
---
- Add missing `healthcheck` for local "broker" container
---

Release 7.0.10 - Add missing `healthcheck` for local-development "broker" container

---

Dockerfile
README.md
application/run.sh

- Added Parameter Store as an alternative to AppConfig
- Fixed incorrect link in README
- README whitespace autoformat corrections
---

Release 7.1.0 -- add Parameter Store as an alternative to AppConfig

---

Dockerfile

- Removed config-shim from Dockerfile to use the version in the silintl/php8 base image

Release 7.2.1 -- remove config-shim to use the version in the silintl/php8 base image

---

application/composer.lock
application/dependencies.json

[IDP-1475](https://itse.youtrack.cloud/issue/IDP-1475) idp-pw-api alert #27: CVE-2025-27773
---
- Update simplesamlphp/saml2 to 4.17.0
---

Release 7.3.1 -- update simplesamlphp/saml2 to 4.17.0

---

application/common/components/passwordStore/Ldap.php

https://support.gtis.sil.org/issue/IDP-1540
---
- findByOrFail returns Model|array, so appending `|array` to the calls and adjusting parameters throughout class.
---

Release 7.3.4 - Return `LDAP_Entry|array` for findUser calls

---

application/composer.json
application/composer.lock
application/dependencies.json

[IDP-1506](https://support.gtis.sil.org/issue/IDP-1506) idp-pw-api alert #28: CVE-2024-58136
---
- Removed fillup/fake-bower-assets
- Updated dependences for CVE-2024-4990
---

Release 7.3.6 -- update dependences, remove fillup/fake-bower-assets

---

.github/workflows/test-and-publish.yml

- Build and deploy to Docker Hub on all branches. This can make debugging easier by creating development images for use on staging.

build and deploy to Docker Hub on branches
